kelly/cashier
ChampionFX/champion-static pull request #76
Opened 2017-02-22 09:36 UTC by kellybinary

Add Deposit and Withdrawal page + tidy up.

2017-02-23 08:22 UTC, mohammad-deriv approved these changes

2017-02-27 05:05 UTC, jy-binary commented on src/templates/cashier/deposit_withdraw.html.tt
> +                        [% l("The company holds customer funds in separate bank accounts to the operational accounts which would not, in the event of insolvency, form part of the Company's assets. Th
remove all mention of Gambling Commission

2017-02-27 13:46 UTC, ashkanx requested changes

2017-02-27 13:46 UTC, ashkanx commented on src/templates/cashier/deposit_withdraw.html.tt
> +            <div id="ukgc_funds_protection" class="hidden">
@kellybinary   ukgc_funds_protection is for MX accounts. you don't need to handle this in champion-fx. remind me to explain this tomorrow.

2017-02-27 13:46 UTC, ashkanx commented on src/javascript/pages/cashier/deposit_withdraw.js
> +                            .html('Your account needs age verification. Please contact <a href="[_1]">customer support</a> for more information.'
Same here. age verifications is not required

2017-02-27 13:46 UTC, ashkanx commented on src/javascript/pages/cashier/deposit_withdraw.js
> +                    case 'ASK_CURRENCY': // set account currency to USD if not set // TODO: remove this after currency set by default in backend
add this to a Trello card. we need to remove this when back-end fix is ready

2017-02-28 01:31 UTC, kellybinary commented on src/javascript/pages/cashier/deposit_withdraw.js
> +                    case 'ASK_CURRENCY': // set account currency to USD if not set // TODO: remove this after currency set by default in backend
ok, this is listed as Todo in the card

2017-03-01 02:02 UTC, mohammad-deriv approved these changes

2017-03-01 02:36 UTC, ashkanx approved these changes

2017-03-01 02:36 UTC, merged