design change
ChampionFX/champion-static pull request #78
Opened 2017-03-05 14:05 UTC by nazaninreihani

2017-03-09 08:38 UTC, binary-hamedanchi commented on src/javascript/common/header.js
> +            $('#main-signup').removeClass('hidden');
What do you think about `$('#main-login, #main-signup').removeClass('hidden');`?

2017-03-09 08:43 UTC, mohammad-deriv requested changes

2017-03-09 08:43 UTC, binary-hamedanchi commented on src/templates/layout/includes/slider.html.tt
> +                      <h3 class="bold white">[% l('ChampionFX: Where the Client is King') %]</h3>
Can we use `<strong>` here and remove the `.bold` declaration?

2017-03-09 08:44 UTC, nazaninreihani commented on src/templates/layout/includes/slider.html.tt
> +                      <h3 class="bold white">[% l('ChampionFX: Where the Client is King') %]</h3>
yes sure

2017-03-09 09:13 UTC, mohammad-deriv requested changes

2017-03-09 09:13 UTC, mohammad-deriv commented on src/sass/champion.scss
> +    #license-box-container {
```css
#end_note, #license-box-container {
    display: none;
}
```

2017-03-09 09:13 UTC, binary-hamedanchi commented on src/sass/champion_overwrite.scss
> +    height: 45px;
Can we have all the above selectors having `height: 45px;` together?

2017-03-09 09:13 UTC, binary-hamedanchi commented on src/sass/slider.scss
> +            height: 100%;
```css
.container {
    &, .row {
        height: 100%;
    }
}
```

2017-03-09 09:13 UTC, binary-hamedanchi commented on src/templates/layout/includes/header.html.tt
> +                      [% l('About') %]
Please check the indentations of the changes in this PR as well.
Thanks.

2017-03-09 12:20 UTC, nazaninreihani commented on src/sass/champion_overwrite.scss
> +    height: 45px;
isn't it just the logo?

2017-03-10 03:00 UTC, mohammad-deriv approved these changes

2017-03-10 03:21 UTC, merged